FROM centos:7
#
# See https://hub.docker.com/_/centos/
# for Dockerfile for systemd
#

RUN yum -y update && yum -y install systemd && \ 
    yum clean all

RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == \
systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;
VOLUME [ "/sys/fs/cgroup" ]

RUN yum -y update && yum install -y openssh-server && \
    yum clean all && \
    /usr/bin/ssh-keygen -A && \
    systemctl enable sshd.service && \
    mkdir /var/run/sshd && \
    useradd ansible -s /bin/bash && \
    mkdir -p /home/ansible/.ssh/ && \
    chmod 0700 /home/ansible/.ssh/ 

RUN yum -y update && yum install -y sudo && \
    yum install -y procps && \
    yum install -y iproute && \ 
    yum clean all 

COPY ansible_ssh_config /home/ansible/.ssh/config
COPY id_rsa_ansible /home/ansible/.ssh/id_rsa
COPY id_rsa_ansible.pub /home/ansible/.ssh/id_rsa.pub
COPY id_rsa_ansible.pub /home/ansible/.ssh/authorized_keys

RUN chmod 0600 /home/ansible/.ssh/authorized_keys

RUN chown -R ansible:ansible /home/ansible/ && \
    echo "ansible ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

RUN rm -f /usr/lib/tmpfiles.d/systemd-nologin.conf

ENV container docker

EXPOSE 22
CMD ["/usr/sbin/init"]
