---

url_apt_key: https://www.mongodb.org/static/pgp/server-{{ mongodb_version_repo }}.asc
mongodb_repository: "deb http://repo.mongodb.org/apt/debian {{ ansible_distribution_release }}/mongodb-org/{{ mongodb_version_repo }} main"

mongodb_packages_dependencies:
  - python-pip

mongodb_packages:
  - mongodb-org={{mongodb_version}}
  - mongodb-org-server={{mongodb_version}}
  - mongodb-org-shell={{mongodb_version}}
  - mongodb-org-mongos={{mongodb_version}}
  - mongodb-org-tools={{mongodb_version}}
