---

- name: Include distribution-specific variables [Ubuntu].
  tags: [common, ubuntu]
  include_vars: "{{ ansible_distribution }}.yml"
  when: ansible_distribution == 'Ubuntu'

- name: Install any necessary dependencies [Debian/Ubuntu]
  tags: [common, debian, ubuntu]
  apt: pkg={{ item }} state=present
  with_items: "{{ mongodb_packages_dependencies | default([]) }}"

- name: Add Debian apt signing key
  tags: [common, debian]
  apt_key: 
    url: "{{ url_apt_key }}"
    state: present
  when: ansible_distribution == 'Debian'

- name: Add Ubuntu apt signing key by id
  tags: [common, ubuntu]
  apt_key:
    keyserver: "{{ url_apt_key }}"
    id: "{{ id_apt_key }}"
  when: ansible_distribution == 'Ubuntu'

- name: Add Mongodb repository [Debian/Ubuntu]
  tags: [common, debian, ubuntu]
  apt_repository: repo='{{ mongodb_repository }}' update_cache=yes

- name: Install mongodb packages [Debian/Ubuntu]
  tags: [common, debian, ubuntu]
  apt: pkg={{ item }} state=present force=yes
  with_items: "{{ mongodb_packages }}"
