---

- name: Install epel-release [CentOS]
  yum: name=epel-release state=present
  when: ansible_distribution == 'CentOS'

- name: Install any necessary dependencies [RedHat/CentOS]
  yum: name={{ item }} state=present
  with_items: "{{ mongodb_packages_dependencies | default([]) }}"

- name: Add mongodb repository [RHEL/CentOS]
  yum_repository:
    name: mongodb-org-{{ mongodb_version_repo }}
    description: MongoDB Repository
    baseurl: "{{ mongodb_repo_baseurl }}"
    gpgcheck: "{{ mongodb_repo_gpgcheck }}"
    gpgkey: "{{ mongodb_repo_gpgkey }}"

- name: Install mongodb packages [RHEL/CentOS]
  yum: name={{ item }} state=present
  with_items: "{{ mongodb_packages }}"

- name: Install additional packages [RHEL/CentOS]
  yum: name={{ item }} state=present
  with_items: "{{ mongodb_additional_packages | default([]) }}"
